### ISSUE TITLE
SSL in dashboard and unsecured flags images

### ISSUE THREAD

**Issue by beherit** [ceceppa/ceceppa-multilingua#10]
I have enabled SSL in dashboard and with ceceppa-multilingua plugin I have problem with secure because plugin always added unsecure URL to CSS:

`
<link rel='stylesheet' id='ceceppaml-flags-css'  href='http://mypage.com/wp-content/uploads/ceceppaml/cache/cml_flags.css?ver=4.1' type='text/css' media='all' />
`

Problem disappeared when I uncommented line for definition CML PLUGIN CACHE URL:
`
define( 'CML_PLUGIN_CACHE_URL', CML_PLUGIN_URL . trailingslashit ( 'cache' ) );
`
and commented second definition:
`
define( 'CML_PLUGIN_CACHE_URL', CML_UPLOAD_URL . trailingslashit ( 'cache' ) );
`
Please fix it.

**Comment by ceceppa** [comment]
Hi,
I just added a check in the code... If ssl is active the url will be "https" instead of "http"...

Thanks for the report
