### ISSUE TITLE
Page already sent...

### ISSUE THREAD

**Issue by overclokk** [ceceppa/ceceppa-multilingua#12]
Ciao Alessandro, appena attivato su nuovo sito mi ha dato questo errore, di solito è causato da uno spazio dopo la chiusura del php ?>, io ho trovato che potrebbe essere nel file settings.php, eliminando lo spazio non mi è più capitato.

Eventualmente puoi non chiudere i file php.

Ciao

**Comment by ceceppa** [comment]
Grazie per la segnalazione... 
Per quanto riguarda i "?>", di chiusura, li sto togliendo dai file, man mano che li "incontro"... :)
