### ISSUE TITLE
shortcode [:it]testo[/:it] nell'excerpt

### ISSUE THREAD

**Issue by rexromae** [ceceppa/ceceppa-multilingua#15]
@ceceppa è possibile usare lo short code

[:en]English text here.[/:en]
[:ar]Arabic text here[/:ar]

nel excerpt? Ho provato ma sembra non funzionare. Sarebbe molto utile per noi, pensi di poterlo aggiungere?

**Comment by ceceppa** [comment]
Non ti funzione perche' di default wp non "esegue" gli shortcode per gli excerpt. devi utilizzare una soluzione simile:

echo do_shortcode( get_the_excerpt()  );
