### ISSUE TITLE
Warning array_diff

### ISSUE THREAD

**Issue by Mte90** [ceceppa/ceceppa-multilingua#16]
I get this warning in the backend 
![bug](https://cloud.githubusercontent.com/assets/403283/7352055/784a8e54-ed09-11e4-8829-2aea58589f11.png)
![bug1](https://cloud.githubusercontent.com/assets/403283/7352056/78dc0398-ed09-11e4-8a42-c52774fefd5e.png)

**Comment by ceceppa** [comment]
Ecchisenefrega :dancer: . Fixed :)

**Comment by Mte90** [comment]
![foto6](https://cloud.githubusercontent.com/assets/403283/7838631/403c1ab8-048e-11e5-9c97-96be09ed5a43.png)
maybe is related
