### ISSUE TITLE
Reseting front page static page

### ISSUE THREAD

**Issue by beherit** [ceceppa/ceceppa-multilingua#17]
After activation this plugin I have problem with resetting the chosen static page displayed as front page of my site (options-reading.php). In option "Front page displays" I have chosen "A static page (select below)" and selected page in "Front page", "Posts page" is blank. From time to time the "Front page" option is resets and chosen random a static page. I have this issue on my all page with ceceppa.

**Comment by ceceppa** [comment]
Hi,
to avoid this just go in "Ceceppa Multilingua" -> "Settings" -> "Advanced" uncheck the option under "Static page". 
In the meanwhile I'll carry on to fix the bug...

**Comment by beherit** [comment]
Uh but now I have problem with is_front_page() function :(

**Comment by ceceppa** [comment]
Ok... Once come back from work, I'll try to fix the bug...

**Comment by beherit** [comment]
Any news?

**Comment by ceceppa** [comment]
Hi,
I just made some changes to fix the issue... For now the update is available only on the git version

**Comment by beherit** [comment]
Thank You :) I'll test it and I'll let you know.

**Comment by beherit** [comment]
It's a problem - now I can't add new page, only new post :/

**Comment by beherit** [comment]
Unfortunately, the fix doesn't work.

**Comment by ceceppa** [comment]
Hi,
just made some changes to avoid it...

**Comment by beherit** [comment]
Now is better but still is problem when I editing front page. It doesn't matter whether published or only a preview page changes.

**Comment by ceceppa** [comment]
Hi,
sorry for delay... I just fixed the issue with the front page too

**Comment by beherit** [comment]
Problem doesn't exist anymore :)
