### ISSUE TITLE
SEO YOAST Breadcrumbs error for second level sub-category

### ISSUE THREAD

**Issue by ChairmanMao242** [ceceppa/ceceppa-multilingua#29]
While using SEO Yoast breadcrumbs for posts, all is correct until you have only one level deep category.

When you have a sub-category (for example a post that is behind "cars" - "old cars"), the subcategory in the breadcrumbs is not translated.

![Screenshot](http://www.salesspa.com/breadcrumbs-error.png)

**Comment by ChairmanMao242** [comment]
This issue due to wp_get_object_terms used in WP SEO Breadcrumbs for manipulating post anchestors.
This function is not translated via filter hook in frontend/frontend.php in CECEPPA plugin.

So it needs to add following line after line 65 in frontend/frontend.php
,,,
   	add_filter( 'wp_get_object_terms', array( & $this, 'translate_terms' ), 10, 2 );
,,,

**Comment by ceceppa** [comment]
thanks for the suggestion
