### ISSUE TITLE
Bug when i choose the other language

### ISSUE THREAD

**Issue by Mte90** [ceceppa/ceceppa-multilingua#31]
I've choosen a different language for my article and in the category box i get an empty list
![19](https://cloud.githubusercontent.com/assets/403283/9060199/d9aa9810-3ab1-11e5-8cd9-37ab0dc97104.png)

**Comment by ceceppa** [comment]
Can you check if the update fix the issue?

**Comment by Mte90** [comment]
Resolved finally!
