### ISSUE TITLE
post author rewrites for all linked posts

### ISSUE THREAD

**Issue by dosievskiy-gfl** [ceceppa/ceceppa-multilingua#37]
Could you please change the next line in **\ceceppa-multilingua\admin\admin-posts.php** on line **409**
FROM
`'post_author'   => get_current_user_id(),`
TO
`'post_author'   => $_POST['post_author'],`
?
Cause after creating/updating post - author sets as user you are logged in instead of post author.

**Comment by ceceppa** [comment]
Just fixed the issue.

Thanks for the report
