### ISSUE TITLE
Front page slug

### ISSUE THREAD

**Issue by beherit** [ceceppa/ceceppa-multilingua#38]
There is a problem with slug on front page - with Ceceppa I have 2 URLs for one language:

http://domain.tld/en
http://domain.tld/en/

This two links are not good for SEO. I try to configure permalinks to remove first one but with not luck.

**Comment by ceceppa** [comment]
Hi,
could you  please be more specific? Just had a look on my website I found this 2:

<meta property="og:url" content="http://www.alessandrosenese.eu/" />
<link rel="canonical" href="http://www.alessandrosenese.eu" />

Are you speaking about them?

**Comment by beherit** [comment]
Check my site:

https://beherit.pl/en
https://beherit.pl/en/

And in Google PageSpeed Insights I see error for my sites with Ceceppa, e.g.:
```
Avoid landing page redirects
Your page has 3 redirects. Redirects introduce additional delays before the page can be loaded.
Avoid landing page redirects for the following chain of redirected URLs.

    http://beherit.pl/
    https://beherit.pl/
    https://beherit.pl/en
    https://beherit.pl/en/
```

**Comment by beherit** [comment]
Any news?

**Comment by beherit** [comment]
@ceceppa could You fix it?

**Comment by ceceppa** [comment]
Just updated the github version of the plugin. Now redirect only once, after added the language slug.
Can you check if works fine for you?

Thanks

**Comment by beherit** [comment]
@ceceppa I don't see any new commit, last was 14 days ago.

**Comment by ceceppa** [comment]
My bad, forgot to push :)

**Comment by beherit** [comment]
Now it works fine :)
