### ISSUE TITLE
Problem after update to 1.5.13

### ISSUE THREAD

**Issue by beherit** [ceceppa/ceceppa-multilingua#39]
After upgrade to version 1.5.13 my site is broken, I don't have rights to access admin.php?page=ceceppaml-language-page, slugs don't  works etc.

**Comment by ceceppa** [comment]
Hi,
I'll check the issue later. For now, you can put back the stable version https://en-gb.wordpress.org/plugins/ceceppa-multilingua/. 
For the redirect issue just edit the file: frontend/frontend.php and change the line #2141 from:

      wp_redirect( $location );

to:

      wp_redirect( trailingslashit( $location ) );

**Comment by beherit** [comment]
It's very strange - I upload version from github and still have problem. I had to restore the database backup.
