### ISSUE TITLE
Search in My Translation

### ISSUE THREAD

**Issue by rexromae** [ceceppa/ceceppa-multilingua#8]
Hi mate, I'm here just to give you a suggestion of improvement for the future. On our site we have 9 pages of strings in "My Translations" and finding a string to edit starts to be really hard. Would be nice to have a search box on top of the "My Translations" page. 

Thanks for your work!

**Comment by ceceppa** [comment]
Can you check now?

**Comment by rexromae** [comment]
@ceceppa search is broke after updating with the latest GitHub version. Before local (in page) search was working, now it doesn't work at all. Can you have a look please?

**Comment by rexromae** [comment]
Also the pagination seems not working for me in My translations. It always display the first page

**Comment by rexromae** [comment]
I have downgraded to 1.4.39 and pagination is working now.

**Comment by ceceppa** [comment]
Fixed... assafa' :dancers:
