### ISSUE TITLE
CSS bug in backend with WP Seo by Yoast

### ISSUE THREAD

**Issue by Mte90** [ceceppa/ceceppa-multilingua#9]
The metabox of Wp Seo by yoast have a little problem of alignment of tabs created by the file admins.css on line 454:

```
.advanced {
    background: none repeat scroll 0% 0% #FFF;
    cursor: default !important;
    overflow: hidden;
    transition: all 0.2s ease-in-out 0s;
    display: block !important;
}
```
The problem is display block

**Comment by Mte90** [comment]
the problem persist

**Comment by ceceppa** [comment]
Did you try the git version?

**Comment by Mte90** [comment]
Tested with the new admin.css but the problem persist, the problem is the display block :-/
maybe a better selector fix the problem.

**Comment by ceceppa** [comment]
I did... I changed the line from:

.advanced {

to 

.cml-wrap .advanced {

Can you check if your admin.css contains this change?

**Comment by Mte90** [comment]
the cache -.-'
problem fixed.
